import { Expression } from './expression';

export const mockExpressions: Expression[] = [
  {
    id: 'expr_001',
    parentId: null,
    text: 'Biodiversity is crucial for maintaining the balance of ecosystems. It ensures natural sustainability for all life forms. The loss of biodiversity can lead to the collapse of ecosystems, which can have dire consequences for humanity. Protecting biodiversity is essential for food security, health, and the overall well-being of the planet. Efforts to conserve biodiversity must be prioritized to safeguard our future.',
    createdAt: '2024-09-26T12:00:00Z',
    author: {
      id: 'user_001',
      name: 'Alice Johnson',
      avatarUrl: 'https://example.com/avatar1.jpg',
    },
    supportCount: 120,
    opposeCount: 5,
    commentCount: 30,
    shareCount: 10,
    bookmarkCount: 20,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Biodiversity',
    },
  },
  {
    id: 'expr_002',
    parentId: null,
    text: 'Climate change represents one of the most significant challenges facing humanity today. It affects weather patterns, sea levels, and the overall health of our planet. The increasing frequency of extreme weather events is a clear indication of the changes we are experiencing. Addressing climate change requires a collective effort from individuals, governments, and organizations worldwide. Transitioning to renewable energy sources and implementing sustainable practices are vital steps in combating this global crisis.',
    createdAt: '2024-09-26T12:10:00Z',
    author: {
      id: 'user_002',
      name: 'Bob Smith',
      avatarUrl: 'https://example.com/avatar2.jpg',
    },
    supportCount: 150,
    opposeCount: 10,
    commentCount: 25,
    shareCount: 15,
    bookmarkCount: 35,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Climate_change',
    },
  },
  {
    id: 'expr_003',
    parentId: null,
    text: 'The transition to renewable energy sources is not just an environmental necessity but also an economic opportunity. By investing in solar, wind, and other renewable energy technologies, we can create jobs, reduce greenhouse gas emissions, and decrease our reliance on fossil fuels. Countries around the world are recognizing the potential of renewables to drive economic growth while addressing climate change. The future of energy is renewable, and we must embrace this change for a sustainable world.',
    createdAt: '2024-09-26T12:15:00Z',
    author: {
      id: 'user_003',
      name: 'Charlie Brown',
      avatarUrl: 'https://example.com/avatar3.jpg',
    },
    supportCount: 200,
    opposeCount: 8,
    commentCount: 40,
    shareCount: 20,
    bookmarkCount: 50,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Renewable_energy',
    },
  },
  {
    id: 'expr_004',
    parentId: null,
    text: 'Artificial intelligence (AI) is rapidly transforming industries and reshaping our daily lives. From healthcare to finance, AI technologies are enhancing efficiency and enabling new capabilities. However, the rise of AI also brings ethical considerations and challenges. As we integrate AI into various aspects of society, it is crucial to address issues such as privacy, bias, and job displacement. A balanced approach will ensure that AI serves humanity positively.',
    createdAt: '2024-09-26T12:20:00Z',
    author: {
      id: 'user_004',
      name: 'Diana Prince',
      avatarUrl: 'https://example.com/avatar4.jpg',
    },
    supportCount: 180,
    opposeCount: 12,
    commentCount: 15,
    shareCount: 25,
    bookmarkCount: 45,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Artificial_intelligence',
    },
  },
  {
    id: 'expr_005',
    parentId: null,
    text: "Education plays a pivotal role in shaping individuals and societies. It empowers people with knowledge, critical thinking skills, and the ability to contribute meaningfully to their communities. In today's fast-paced world, education must adapt to new technologies and methodologies to prepare future generations for the challenges ahead. Lifelong learning and access to quality education are essential for personal growth and societal progress.",
    createdAt: '2024-09-26T12:25:00Z',
    author: {
      id: 'user_005',
      name: 'Eve Adams',
      avatarUrl: 'https://example.com/avatar5.jpg',
    },
    supportCount: 160,
    opposeCount: 3,
    commentCount: 22,
    shareCount: 30,
    bookmarkCount: 40,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Education',
    },
  },
  {
    id: 'expr_006',
    parentId: null,
    text: 'Mental health awareness is becoming increasingly important as society recognizes the impact of mental health on overall well-being. Stigma surrounding mental health issues often prevents individuals from seeking help. Promoting mental health awareness can lead to better understanding, support, and resources for those in need. It is vital to create an environment where mental health is prioritized and openly discussed, ensuring that everyone has access to the care they deserve.',
    createdAt: '2024-09-26T12:30:00Z',
    author: {
      id: 'user_006',
      name: 'Frank Castle',
      avatarUrl: 'https://example.com/avatar6.jpg',
    },
    supportCount: 140,
    opposeCount: 2,
    commentCount: 18,
    shareCount: 12,
    bookmarkCount: 28,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Mental_health',
    },
  },
  {
    id: 'expr_007',
    parentId: null,
    text: 'Technology has revolutionized communication, breaking down barriers and connecting people across the globe. The rise of social media, instant messaging, and video conferencing has transformed how we interact. However, this shift also raises concerns about privacy, misinformation, and the quality of human interactions. Balancing the benefits of technology with its challenges is essential for fostering healthy communication in our digital age.',
    createdAt: '2024-09-26T12:35:00Z',
    author: {
      id: 'user_007',
      name: 'Grace Lee',
      avatarUrl: 'https://example.com/avatar7.jpg',
    },
    supportCount: 175,
    opposeCount: 7,
    commentCount: 27,
    shareCount: 14,
    bookmarkCount: 33,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Communication_technology',
    },
  },
  {
    id: 'expr_008',
    parentId: null,
    text: 'Space exploration has always captivated human imagination, driving innovation and expanding our understanding of the universe. Current efforts in space exploration, including missions to Mars and beyond, are not only about scientific discovery but also about the potential for human colonization of other planets. As we venture into the cosmos, we must consider the ethical implications and the responsibilities that come with exploring new worlds.',
    createdAt: '2024-09-26T12:40:00Z',
    author: {
      id: 'user_008',
      name: 'Henry Ford',
      avatarUrl: 'https://example.com/avatar8.jpg',
    },
    supportCount: 190,
    opposeCount: 4,
    commentCount: 20,
    shareCount: 18,
    bookmarkCount: 38,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Space_exploration',
    },
  },
  {
    id: 'expr_009',
    parentId: null,
    text: 'The internet has fundamentally changed the way we access information, communicate, and conduct business. Its evolution from a simple network to a vast digital ecosystem has transformed societies worldwide. However, the internet also presents challenges, including cybersecurity threats and the digital divide. As we continue to innovate, it is crucial to ensure that the benefits of the internet are accessible to all, while also safeguarding against its risks.',
    createdAt: '2024-09-26T12:45:00Z',
    author: {
      id: 'user_009',
      name: 'Ivy Wang',
      avatarUrl: 'https://example.com/avatar9.jpg',
    },
    supportCount: 160,
    opposeCount: 6,
    commentCount: 19,
    shareCount: 11,
    bookmarkCount: 29,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Internet',
    },
  },
  {
    id: 'expr_010',
    parentId: null,
    text: 'Cultural heritage encompasses the traditions, customs, and artifacts that shape our identity as a society. Preserving cultural heritage is essential for maintaining a sense of belonging and continuity across generations. In a rapidly globalizing world, it is vital to safeguard diverse cultural expressions and promote understanding among different communities. By valuing cultural heritage, we enrich our collective experience and foster respect for cultural diversity.',
    createdAt: '2024-09-26T12:50:00Z',
    author: {
      id: 'user_010',
      name: 'Jack Sparrow',
      avatarUrl: 'https://example.com/avatar10.jpg',
    },
    supportCount: 155,
    opposeCount: 1,
    commentCount: 16,
    shareCount: 9,
    bookmarkCount: 27,
    childExpressions: [],
    quote: {
      type: 'url',
      content: 'https://en.wikipedia.org/wiki/Cultural_heritage',
    },
  },
  {
    id: '1',
    parentId: null,
    text: 'I just deployed my first app on Heroku! 🎉',
    images: ['https://example.com/image1.jpg'],
    videos: [],
    createdAt: '2024-09-23T12:00:00Z',
    author: {
      id: 'user1',
      name: 'Alice Johnson',
      avatarUrl: 'https://example.com/avatar1.png',
    },
    supportCount: 120,
    opposeCount: 5,
    commentCount: 30,
    shareCount: 15,
    bookmarkCount: 10,
    childExpressions: [],
  },
  {
    id: '2',
    parentId: null,
    text: "What's the best way to learn React? Any tips?",
    images: [],
    videos: [],
    createdAt: '2024-09-25T13:15:00Z',
    author: {
      id: 'user2',
      name: 'Bob Smith',
      avatarUrl: 'https://example.com/avatar2.png',
    },
    supportCount: 75,
    opposeCount: 2,
    commentCount: 12,
    shareCount: 5,
    bookmarkCount: 8,
    childExpressions: [],
  },
  {
    id: '3',
    parentId: null,
    text: 'Just finished reading a great book on JavaScript! 📚',
    images: [],
    videos: [],
    createdAt: '2024-09-26T14:30:00Z',
    author: {
      id: 'user3',
      name: 'Charlie Brown',
      avatarUrl: 'https://example.com/avatar3.png',
    },
    supportCount: 200,
    opposeCount: 1,
    commentCount: 50,
    shareCount: 20,
    bookmarkCount: 25,
    childExpressions: [],
  },
  {
    id: '4',
    parentId: null,
    text: 'Can someone explain closures in JavaScript?',
    images: [],
    videos: [],
    createdAt: '2024-09-26T15:45:00Z',
    author: {
      id: 'user4',
      name: 'Diana Prince',
      avatarUrl: 'https://example.com/avatar4.png',
    },
    supportCount: 50,
    opposeCount: 0,
    commentCount: 8,
    shareCount: 3,
    bookmarkCount: 4,
    childExpressions: [],
  },
  {
    id: '5',
    parentId: null,
    text: 'Excited for the upcoming React conference! 🎤',
    images: [],
    videos: [],
    createdAt: '2024-09-26T16:00:00Z',
    author: {
      id: 'user5',
      name: 'Eve Adams',
      avatarUrl: 'https://example.com/avatar5.png',
    },
    supportCount: 95,
    opposeCount: 1,
    commentCount: 15,
    shareCount: 10,
    bookmarkCount: 6,
    childExpressions: [],
  },
  {
    id: '6',
    parentId: null,
    text: "I'm having trouble with my CSS layout. Help!",
    images: [],
    videos: [],
    createdAt: '2024-09-26T17:15:00Z',
    author: {
      id: 'user6',
      name: 'Frank Castle',
      avatarUrl: 'https://example.com/avatar6.png',
    },
    supportCount: 30,
    opposeCount: 3,
    commentCount: 25,
    shareCount: 2,
    bookmarkCount: 3,
    childExpressions: [],
  },
  {
    id: '7',
    parentId: null,
    text: 'Just completed a coding bootcamp! Ready for the job hunt! 💪',
    images: ['https://example.com/image2.jpg'],
    videos: [],
    createdAt: '2024-09-26T18:30:00Z',
    author: {
      id: 'user7',
      name: 'Grace Lee',
      avatarUrl: 'https://example.com/avatar7.png',
    },
    supportCount: 150,
    opposeCount: 0,
    commentCount: 40,
    shareCount: 12,
    bookmarkCount: 11,
    childExpressions: [],
  },
  {
    id: '8',
    parentId: null,
    text: 'Who else is excited for the new JavaScript features?',
    images: [],
    videos: [],
    createdAt: '2024-09-26T19:45:00Z',
    author: {
      id: 'user8',
      name: 'Henry Ford',
      avatarUrl: 'https://example.com/avatar8.png',
    },
    supportCount: 80,
    opposeCount: 4,
    commentCount: 10,
    shareCount: 5,
    bookmarkCount: 9,
    childExpressions: [],
  },
  {
    id: '9',
    parentId: null,
    text: 'I love using Tailwind CSS for styling!',
    images: [],
    videos: [],
    createdAt: '2024-09-26T20:00:00Z',
    author: {
      id: 'user9',
      name: 'Ivy Green',
      avatarUrl: 'https://example.com/avatar9.png',
    },
    supportCount: 120,
    opposeCount: 2,
    commentCount: 20,
    shareCount: 8,
    bookmarkCount: 7,
    childExpressions: [],
  },
  {
    id: '10',
    parentId: null,
    text: 'What are your thoughts on the latest React updates?',
    images: [],
    videos: [],
    createdAt: '2024-09-26T21:15:00Z',
    author: {
      id: 'user10',
      name: 'Jack Sparrow',
      avatarUrl: 'https://example.com/avatar10.png',
    },
    supportCount: 60,
    opposeCount: 1,
    commentCount: 5,
    shareCount: 3,
    bookmarkCount: 2,
    childExpressions: [],
  },
];
